declare const _default: import("vue").DefineComponent<{}, {
    chatInput: import("vue").Ref<string, string>;
    chatInputRef: import("vue").Ref<null, null>;
    conversations: any;
    messageHandlers: {};
    addMessage: any;
    loadSession: any;
    activeCollectionData: any;
    activeCollectionVideos: any;
    createNewSession: () => void;
    setChatInput: (input: any) => void;
    registerMessageHandler: (contentType: any, handler: any) => void;
    uploadMedia: any;
    $emit: (event: never, ...args: any[]) => void;
    chatInputPlaceholder: string;
    customChatHook: Function;
    chatHookConfig: Record<string, any>;
    size: string;
    headerConfig: Record<string, any>;
    sidebarConfig: Record<string, any>;
    defaultScreenConfig: Record<string, any>;
    $props: {
        readonly chatInputPlaceholder?: string | undefined;
        readonly customChatHook?: Function | undefined;
        readonly chatHookConfig?: Record<string, any> | undefined;
        readonly size?: string | undefined;
        readonly headerConfig?: Record<string, any> | undefined;
        readonly sidebarConfig?: Record<string, any> | undefined;
        readonly defaultScreenConfig?: Record<string, any> | undefined;
    };
}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
export default _default;
